badtuxx/DescomplicandoKubernetes

day-1/DescomplicandoKubernetes-Day1.md
day-2/DescomplicandoKubernetes-Day2.md

Esse pr eu adicionei links para a documentação das palavras em negrito.

Add links to bold words.

---

day-1/DescomplicandoKubernetes-Day1.md

corrige comando de verificacao de virtualizacao

fix readme

---

day-1/DescomplicandoKubernetes-Day1.md

corrige comando de verificacao de virtualizacao

fix linha de instalacao do minikube para Linux

---

Extras/Security_Context.md

Adição de conteúdo sobre  Security Context

Conteudo sobre Security Context

---

CONTRIBUTING.md
README.md
day-1/DescomplicandoKubernetes-Day1.md
day-2/DescomplicandoKubernetes-Day2.md
day-3/DescomplicandoKubernetes-Day3.md

* Adicionando o arquivo README.md
* Adicionando o arquivo CONTRIBUTING.md
* Melhorias no conteúdo do day-1.
* Melhorias no conteúdo do day-2.
* Melhorias no conteúdo do day-3.
* Para facilitar a contribuição de novos membros e para melhorar o conteúdo.

Us aecio 1

---

day-1/DescomplicandoKubernetes-Day1.md

Caso seja aprovado posso complmentar com mais informações

Inclusão de instalação do microk8s  -

---

manutencao-cluster-etcd/ETCD - Backup ETCD.md

Coloquei o tópico para dicas para a CKA sobre o ETCD.
Se tiver alguma sugestão, é só falar que eu reviso e refaço o PR.

Ajustes no nome do backup e dicas para os exames.

---

day-1/DescomplicandoKubernetes-Day1.md

Add comentário sobre a opção --apiserver-advertise-address

Add comentário sobre a opção da inicialização do cluster

---

day-1/DescomplicandoKubernetes-Day1.md

Habilitar e iniciar o serviço do docker em distribuições baseadas no RedHat.

Habilitar e iniciar o serviço do docker

---

day-1/DescomplicandoKubernetes-Day1.md

Ajustes para alterar o driver do cgroup em distribuições baseadas no RedHat.

Ajustes para alterar o driver do cgroup

---

day-1/DescomplicandoKubernetes-Day1.md

Ajusta alguns pequenos erros de digitação.

Update commands in day 01

---

CONTRIBUTING.md
Extras/Security_Context.md
README.md
day-1/DescomplicandoKubernetes-Day1.md
day-2/DescomplicandoKubernetes-Day2.md
day-3/DescomplicandoKubernetes-Day3.md
manutencao-cluster-etcd/ETCD - Backup ETCD.md

Corrigido erros gramaticais e sumário
Para melhorar o conteúdo.

Us aecio 2

---

CONTRIBUTING.md
day-1/DescomplicandoKubernetes-Day1.md

* Adicionada a dica sobre o uso do VSCode e alguns plugins para edição do conteúdo.
* Adicionanda a documentação de instalação do kind.
Para compartilhar dicas de como manter de forma confortável a edição do conteúdo e dar a opção de usar o kind.

Us aecio 3

---

Extras/Security_Context.md
day-1/DescomplicandoKubernetes-Day1.md
day-2/DescomplicandoKubernetes-Day2.md
day-3/DescomplicandoKubernetes-Day3.md
manutencao-cluster-etcd/ETCD - Backup ETCD.md

* Correções ortográficas
* Ajustes na identação dos títulos
* Separação entre comandos e resultados
* Adicionado quebras de linha em comandos grandes
Para melhorar a leitura do conteúdo.

Us aecio 4

---

day-4/DescomplicandoKubernetes-Day4.md

Ajuste de versão para a mais atual onde não é mais usado extensions.
A atualização foi realizada apenas no arquivo **nfs-pv.yaml**, pois era o único necessitando desse ajuste.

[Deployment] [k8s 1.18.2] Ajuste de versão

---

day-2/DescomplicandoKubernetes-Day2.md

Criei um mapa com os comandos mais usados.  acredito que seja útil para quem está começando.

adicionando mapa de principais comandos

---

day-2/DescomplicandoKubernetes-Day2.md
day-4/DescomplicandoKubernetes-Day4.md

Revisado o conteúdo dos dias 2 e 4.
Para melhorar o conteúdo e corrigir erros nos comandos, além de facilitar o entendimento por um leitor iniciante.

Us aecio 5

---

day-1/DescomplicandoKubernetes-Day1.md

Ajustes na instalação do Docker para configurar o Cgroup driver para o `systemd` que é o utilizado e recomendado na [documentação do Kubernetes](https://kubernetes.io/docs/setup/production-environment/container-runtimes/).

Ajustes na instalação do Docker para configurar o Cgroup driver

---

day-1/DescomplicandoKubernetes-Day1.md

Começando a contribuir... revisando o texto ;)

Day-1 : MicroK8S - correção de 'público algo' para 'público alvo'

---

day-1/DescomplicandoKubernetes-Day1.md
day-2/DescomplicandoKubernetes-Day2.md

Objetivo: facilitar o treinamento de quem não tem conta na nuvem, simulando ambiente com múltiplos nó.

Inclusão de configuração multi-nós do kind 

---

Extras/Security-Context/Security_Context.md
day-1/DescomplicandoKubernetes-Day1.md
day-2/DescomplicandoKubernetes-Day2.md
day-3/DescomplicandoKubernetes-Day3.md
day-4/DescomplicandoKubernetes-Day4.md

Pequenos ajustes ortográficos no conteúdo e ajuste no título do day-4
Para melhorar a qualidade da leitura do conteúdo.

Us aecio 6

---

day-1/DescomplicandoKubernetes-Day1.md

Correção ortográfica, reformulação de frases e acréscimo de informações extras para facilitar no entendimento de determinados conceitos ministrados na aula 1.

Revisão textual do documento e acréscimo de descrições extras.

---

day-3/DescomplicandoKubernetes-Day3.md

Padronização das pontuações antes da exibição de código e comandos, e pequenas correções ortográficas.

Pontuações e pequenas correções.

---

Extras/Manutencao-Cluster-Etcd/ETCD - Backup ETCD.md
Extras/Security-Context/Security_Context.md
day-1/DescomplicandoKubernetes-Day1.md
day-2/DescomplicandoKubernetes-Day2.md
day-3/DescomplicandoKubernetes-Day3.md
day-4/DescomplicandoKubernetes-Day4.md

- Revisão do conteúdo sobre o uso do Kind com múltiplos nodes
- Correção ortográfica e melhoria na formatação de todos os arquivos
- Melhoria no conteúdo do day-3
- Melhoria no conteúdo do day-4
- Melhoria no conteúdo dos assuntos extras
**Por que que foi feito?**
Para melhorar a leitura do conteúdo e manter um padrão na sintaxe/formatação.

Us aecio 7

---

day-4/DescomplicandoKubernetes-Day4.md

Incluindo restart do serviço após instalação e configuração (para Debian/Ubuntu e CentOS/RedHat)

Restart do serviço NFS

---

day-3/DescomplicandoKubernetes-Day3.md

Exemplo mencionado na super aula do dia 3 de como criar um deployment a partir do template

Dia 3 - Criando deployment a partir do template

---

day-2/DescomplicandoKubernetes-Day2.md

docs: Day 2 - Algumas correção ortográfica e adição Session Affinity timeout

Us clayton coelho

---

day-2/DescomplicandoKubernetes-Day2.md

Adicionado como colocar/tirar o nó do modo manutenção.

Adicionado o cordon/uncordon

---

Extras/csr-user.md
README.md
day-1/DescomplicandoKubernetes-Day1.md
day-2/DescomplicandoKubernetes-Day2.md
day-3/DescomplicandoKubernetes-Day3.md

Algumas melhorias nos comandos e conteúdo.
Para manter a qualidade e coerência dos comandos e conteúdo.

Us aecio 10

---

CONTRIBUTING.md
Extras/Dicas_prova.md
README.md
day-1/DescomplicandoKubernetes-Day1.md
day-2/DescomplicandoKubernetes-Day2.md
day-3/DescomplicandoKubernetes-Day3.md
day-4/DescomplicandoKubernetes-Day4.md
day-5/DescomplicandoKubernetes-Day5.md
day-6/DescomplicandoKubernetes-Day6.md

* Melhorias na formatação do conteúdo;
* Adição de referências para a certificação CKA e CKAD;
* Ajuste nos links da página inicial;
* Revisão de texto;
* Melhoria nas instruções do arquivo CONTRIBUTING.md;
* Correção de bugs.
* Para melhorar a qualidade do conteúdo e experiência da leitura;
* Para facilitar a colaboração/edição de conteúdo.

Us aecio 11

---

day-3/DescomplicandoKubernetes-Day3.md

Corrigido o nome da imagem ao criar o arquivo yaml do primeiro deployment.

Corrigido o nome da imagem do nginx

---

day-1/DescomplicandoKubernetes-Day1.md

Day 1 - Adicionado no topico do Minikube um exemplo para criacao de multi-node clusters

Day 1 - Adicionado no topico do Minikube um exemplo para criacao de multi-node clusters

---

README.md
day-4/DescomplicandoKubernetes-Day4.md

- Adicionada as definições do RBAC, Role, ClusterRole, RoleBinding e ClusterRoleBinding.
- Atualizada a apiVersion ``rbac.authorization.k8s.io/v1beta1`` para ``rbac.authorization.k8s.io/v1``
- Reestruturação de como criar ServiceAccount e ClusterRoleBinding na unha e através de um manifesto.
- Adicionado no Readme do projeto os subtópicos: Role e ClusterRole, RoleBinding e ClusterRoleBinding.
Todas as informações foram adicionadas conforme o curso e a documentação.

Alterado o Day4 - RBAC

---

Extras/Dicas_prova.md
README.md
day-1/DescomplicandoKubernetes-Day1.md
day-3/DescomplicandoKubernetes-Day3.md
day-4/DescomplicandoKubernetes-Day4.md
day-5/DescomplicandoKubernetes-Day5.md
day-6/DescomplicandoKubernetes-Day6.md

- Corrige alguns typos.
- Remove trailing whitespaces.

Corrige typos

---

day-1/DescomplicandoKubernetes-Day1.md
day-4/DescomplicandoKubernetes-Day4.md

* Atualização do kind para dar suporte ao Kubernetes 1.19.1;
* Atualização do minikube, microk8s, k3s, kubectl e kubeadm para dar suporte ao Kubernetes 1.19.1;
* Melhorias no conteúdo do dia 1;
* Melhorias no conteúdo do dia 4.
* Para melhorar a qualidade do conteúdo;
* Utilizar a versão mais recentes do Kubernetes;
* Manter o padrão de formação do conteúdo e comandos.

Us aecio 12

---

day-5/DescomplicandoKubernetes-Day5.md

Atualização do conteúdo do day-5

Diegoaceneves day5

---

day-4/DescomplicandoKubernetes-Day4.md

Correcao minima para permitir a execucao do script de instalacao do helm3

Correcao minima para permitir a execucao do script de instalacao do helm3

---

day-4/DescomplicandoKubernetes-Day4.md

Atualização dos repositórios do Prometheus e do Grafana que estão depreciados no repositório stable (https://kubernetes-charts.storage.googleapis.com/)

Day4 - Atualização de repostórios do Prometheus e Grafana no Helm

---

Extras/pod-security-policy.md

Melhoria no conteúdo do arquivo **pod-security-policy.md**
Para corrigir erros de ortografia e melhorar a qualidade da leitura do conteúdo.

Adjust in content of pod-security-policy.md file

---

.gitignore

Criei está configuração para me ajudar a seguir na prática todos os Lab do curso estou com dificuldades em contratar um ambiente em cloud.

Cluster k8s with vragrant

---

.gitignore

Reverts badtuxx/DescomplicandoKubernetes#116

Revert "Cluster k8s with vragrant"

---

cloud-providers/README.md
cloud-providers/azure/README.md
cloud-providers/azure/aks-helloworld-one.yaml
cloud-providers/azure/aks-helloworld-two.yaml
cloud-providers/azure/hello-world-ingress.yaml

Foi realizado uma breve descrição do que foi passado na live de domingo (31/01/2021) para que as pessoas possam revisar e relembrar os comandos utilizados na live.
A criação do diretório ```cloud-provider``` é para que outras pessoas possam adicionar as configurações de outros provedores como AWS e GCP.
A descrição de toda a live está incompleta, faltam:
- Definição das variaveis de ambiente
- Instalação do cert-manager
- Criação da aplicação exemplo
- Criação da rota de entrada
Não pude finalizar por agora esta documentação por motivos de tenho que estar de pé as 8h BR para trabalhar.
https://www.youtube.com/watch?v=zT6qDKf87Do
https://azure.microsoft.com/en-us/free/
https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough
https://docs.microsoft.com/en-us/azure/aks/ingress-tls …

Criando e configurando um cluster Kubernetes no Azure AKS #AULAOKUBERNETES

---

day-1/DescomplicandoKubernetes-Day1.md

O link de instalação do kind não está funcionando. Adicionado o link atualizado da página do kind.

Update DescomplicandoKubernetes day-1 .md

---

pt/day_four/descomplicando_kubernetes.md
pt/day_one/descomplicando_kubernetes.md
pt/day_three/descomplicando_kubernetes.md
pt/day_two/descomplicando_kubernetes.md
pt/extras/cloud-providers/cloud-providers.md

** O que foi feito?**
Revisão de todo o conteúdo do livro.
** Por que foi feito?**
Para melhorar a leitura e execução do conteúdo, além de atualizar alguns comandos em desuso.

Us aecio 16

---

pt/extras/exame_tips.md

Atualizar link para o "Básico de ETCD para backup e restore"

Atualizar link
